version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farmmate_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - farmmate_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: farmmate_frontend_prod
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - farmmate_net

networks:
  farmmate_net:
    driver: bridge
