"""add user profiles

Revision ID: 66dd478a30f6
Revises: 49fc5563aa3d
Create Date: 2026-06-13 20:02:26.865768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66dd478a30f6'
down_revision: Union[str, Sequence[str], None] = '49fc5563aa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('langchain_pg_collection')
    # op.drop_index(op.f('idx_fts_search'), table_name='langchain_pg_embedding', postgresql_using='gin')
    # op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.drop_table('langchain_pg_embedding')
    # op.drop_table('langchain_pg_docstore')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    # op.create_table('langchain_pg_docstore',
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_docstore_pkey'))
    # )
    # op.create_table('langchain_pg_embedding',
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('fts_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, (document)::text)", persisted=True), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    # )
    # op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.create_index(op.f('idx_fts_search'), 'langchain_pg_embedding', ['fts_vector'], unique=False, postgresql_using='gin')
    # op.create_table('langchain_pg_collection',
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey')),
    # sa.UniqueConstraint('name', name=op.f('langchain_pg_collection_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # ### end Alembic commands ###
